services:

    # timekeeping manager
    obos.manager.timestamp:
        class: Obos\Bundle\TimekeepingBundle\Manager\TimestampManager
        arguments:
            - '@request_stack'
            - '@doctrine'
            - 'Timestamp'
        calls:
            - [setUser, ['@security.token_storage']]

    # timestamp form
    obos.form.type.timestamp:
        class: Obos\Bundle\TimekeepingBundle\Form\Type\TimestampType
        arguments:
            - '@security.token_storage'
        calls:
            - [setProjectManager, ['@obos.manager.project']]
        tags:
            - { name: 'form.type', alias: 'timestamp' }
