services:

    # timekeeping manager
    obos.manager.timestamp:
        class: Obos\Bundle\TimekeepingBundle\Manager\TimestampManager
        arguments:
            - '@request_stack'
            - '@doctrine'
            - 'Timestamp'
        calls:
            - [setUser, ['@security.token_storage']]
