services:

    # invoice manager
    obos.manager.invoice:
        class: Obos\Bundle\BillingBundle\Manager\InvoiceManager
        arguments:
            - '@request_stack'
            - '@doctrine'
            - 'Invoice'
        calls:
            - [setUser, ['@security.token_storage']]

    # payment manager
    obos.manager.payment:
        class: Obos\Bundle\BillingBundle\Manager\PaymentManager
        arguments:
            - '@request_stack'
            - '@doctrine'
            - 'Payment'
        calls:
            - [setUser, ['@security.token_storage']]

    # invoice form
    obos.form.type.invoice:
        class: Obos\Bundle\BillingBundle\Form\Type\InvoiceType
        arguments:
            - '@security.token_storage'
        calls:
            - [setProjectManager, ['@obos.manager.project']]
        tags:
            - { name: 'form.type', alias: 'invoice' }

    # payment form
    obos.form.type.payment:
        class: Obos\Bundle\BillingBundle\Form\Type\PaymentType
        arguments:
            - '@security.token_storage'
        calls:
            - [setInvoiceManager, ['@obos.manager.invoice']]
        tags:
            - { name: 'form.type', alias: 'payment' }
