obos_project_management:
    resource: "@ObosProjectManagementBundle/Controller/"
    type:     annotation
    prefix:   /

obos_timekeeping:
    resource: "@ObosTimekeepingBundle/Controller/"
    type:     annotation
    prefix:   /

obos_billing:
    resource: "@ObosBillingBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
