admin:
    resource: "@ObosAdminBundle/Controller/"
    type:     annotation
    prefix:   /

core:
    resource: "@ObosCoreBundle/Controller/"
    type:     annotation
    prefix:   /

projectmanagement:
    resource: "@ObosProjectManagementBundle/Controller/"
    type:     annotation
    prefix:   /

timekeeping:
    resource: "@ObosTimekeepingBundle/Controller/"
    type:     annotation
    prefix:   /

billing:
    resource: "@ObosBillingBundle/Controller/"
    type:     annotation
    prefix:   /
