# you can read more about security in the related section of the documentation
# http://symfony.com/doc/current/book/security.html
security:
    # password encoders
    encoders:
        Obos\Bundle\CoreBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    # role hierarchy
    role_hierarchy: ~

    # user providers
    providers:
        obos_users:
            entity:
                class: Obos\Bundle\CoreBundle\Entity\User
                property: email

    # the main part of the security, where you can set up firewalls
    # for specific sections of your app
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            anonymous: ~

        main:
            provider: obos_users
            form_login:
                login_path: core_root
                check_path: core_login
                default_target_path: core_root
                username_parameter: _email
                password_parameter: _password
            logout:
                path: core_logout
                target: core_root
            anonymous: ~

    # access control
    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/(projects|timeclock|billing), roles: ROLE_CONSULTANT }
