services:
    
    # client manager
    obos.manager.client:
        class: Obos\Bundle\ProjectManagementBundle\Manager\ClientManager
        arguments:
            - '@doctrine'
            - 'Client'
        calls:
            - [setUser, ['@security.context']]
