services:
    
    # client manager
    obos.manager.client:
        class: Obos\Bundle\ProjectManagementBundle\Manager\ClientManager
        arguments:
            - '@request_stack'
            - '@doctrine'
            - 'Client'
        calls:
            - [setUser, ['@security.token_storage']]

    # project manager
    obos.manager.project:
        class: Obos\Bundle\ProjectManagementBundle\Manager\ProjectManager
        arguments:
            - '@request_stack'
            - '@doctrine'
            - 'Project'
        calls:
            - [setUser, ['@security.token_storage']]

    # task manager
    obos.manager.task:
        class: Obos\Bundle\ProjectManagementBundle\Manager\TaskManager
        arguments:
            - '@request_stack'
            - '@doctrine'
            - 'ProjectTask'
        calls:
            - [setUser, ['@security.token_storage']]

    # client form
    obos.form.type.client:
        class: Obos\Bundle\ProjectManagementBundle\Form\Type\ClientType
        arguments:
            - '@security.token_storage'
        tags:
            - { name: 'form.type', alias: 'client' }

    # project form
    obos.form.type.project:
        class: Obos\Bundle\ProjectManagementBundle\Form\Type\ProjectType
        arguments:
            - '@security.token_storage'
        calls:
            - [setClientManager, ['@obos.manager.client']]
        tags:
            - { name: 'form.type', alias: 'project' }

    # task form
    obos.form.type.task:
        class: Obos\Bundle\ProjectManagementBundle\Form\Type\TaskType
        arguments:
            - '@security.token_storage'
        calls:
            - [setProjectManager, ['@obos.manager.project']]
        tags:
            - { name: 'form.type', alias: 'task' }
