services:
    
    # client manager
    obos.manager.client:
        class: Obos\Bundle\ProjectManagementBundle\Manager\ClientManager
        arguments:
            - '@request_stack'
            - '@doctrine'
            - 'Client'
        calls:
            - [setUser, ['@security.context']]

    # client form
    obos.form.type.client:
        class: Obos\Bundle\ProjectManagementBundle\Form\Type\ClientType
        arguments:
            - '@security.token_storage'
        tags:
            - { name: 'form.type', alias: 'client' }
