services:

    # user manager
    obos.manager.user:
        class: 'Obos\Bundle\CoreBundle\Manager\UserManager'
        arguments:
            - '@request_stack'
            - '@doctrine'
            - 'User'
            - '@security.password_encoder'

    # registration form
    obos_core.form.type.registration:
        class: 'Obos\Bundle\CoreBundle\Form\Type\RegistrationType'
        tags:
            - { name: 'form.type', alias: 'registration' }
